name: Deploy to Netlify

on:
  push:
    branches:
      - main
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [testing, production]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: |
          if [ "${{ matrix.environment }}" == "testing" ]; then
            cp .env.testing .env;
          elif [ "${{ matrix.environment }}" == "production" ]; then
            cp .env.production .env;
          fi
          npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1.3
        with:
          publish-dir: ./build
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets[`NETLIFY_SITE_ID_${{ matrix.environment | upper }}`] }}